version: '3.4'
services:
  sqlinjection:
    image: 'walkowiczf/sqlinjection:doaflipv2'
    network_mode: "host"
    privileged: true
    restart: always
    ports:
      - "3306:3306"
      - "41061:22"
      - "41062:80"
    volumes:
      - "~/my_web_pages:/www"
    environment:
      - MYSQL_ROOT_PASSWORD=mysql